name: API Key Authentication

on: [push]

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run API request script with secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py
