name: GitHub Variable Scope Demo

# ✅ Workflow-level variable
env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

on:
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  job1:
    name: Job 1 - First Job
    # 💼 Job-level variable (overrides workflow-level)
    env:
      MY_VAR: "Job 1 level value"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Step 1 - No override
        run: |
          echo "Step 1: MY_VAR = $MY_VAR"
          echo "Using context: ${{ env.MY_VAR }}"

      - name: Step 2 - Override MY_VAR at step level
        env:
          MY_VAR: "Step level value"
        run: |
          echo "Step 2: MY_VAR = $MY_VAR"
          echo "Using context: ${{ env.MY_VAR }}"

  job2:
    name: Job 2 - See if job1's variable is visible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Step 1 - Use MY_VAR in job2
        run: |
          echo "Job 2 Step: MY_VAR = $MY_VAR"
          echo "Using context: ${{ env.MY_VAR }}"
