name: GitHub Variable Scope Demo

# ✅ Workflow-level variable
env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

on:
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  demo-job:
    # ✅ Job-level variable
    env:
      MY_JOB_VARIABLE: "This is a job-level variable"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Workflow & Job Variables
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"

      - name: Step with its own variable
        # ✅ Step-level variable
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"
          echo "Step Variable: $MY_STEP_VARIABLE"

