# This is a basic workflow to help you get started with Actions

name: Github Variable Scope Demo

env:
  MY_WORKFLOW_VARIABLE: "This is my workflow variable"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  demo-job:
    # ✅ Job-level variable
    env:
      MY_JOB_VARIABLE: "This is a job-level variable"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Workflow & Job Variables
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"

      - name: Step with its own variable
        # ✅ Step-level variable
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"
          echo "Step Variable: $MY_STEP_VARIABLE

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
